import type { Metadata } from "next";
import { Noto_Sans_Bengali } from "next/font/google";
import "../globals.css";
import bgImage from "@/assets/bg-masjid.jpg";

const notoSansBengali = Noto_Sans_Bengali({
  subsets: ["bengali"],
  variable: "--font-noto-sans-bengali",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansBengali.variable} antialiased`}>
        <main
          className="w-full h-screen relative bg-cover bg-center"
          style={{ backgroundImage: `url(${bgImage.src})` }}
        >
          {/* Overlay */}
          <div className="absolute inset-0 bg-black/60 z-0"></div>

          {/* Content */}
          <div className="relative z-10 flex items-center justify-center w-full h-full">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
