import type { Metadata } from "next";
import { Noto_Sans_Bengali } from "next/font/google";
import "../globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "@/components/AppSidebar";
import Navbar from "@/components/navbar/Navbar";

const notoSansBengali = Noto_Sans_Bengali({
  subsets: ["bengali"],
  variable: "--font-noto-sans-bengali",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansBengali.variable} antialiased flex`}>
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full">
            <Navbar />
            <div className="py-10 px-6">{children}</div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
